name: Release

on:
  push:
    branches:
      - main   
  workflow_dispatch:
    inputs:
      manual:
        description: "Trigger Release (true/false)"
        required: false
        default: "false"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' 

      - name: Install dependencies
        run: npm install

      - name: Build mod ZIP
        run: npm run build

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
